// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.demo.grpc.proto;

/**
 * Protobuf enum {@code com.demo.grpc.proto.ActionType}
 */
public enum ActionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN_ACTION = 0;</code>
   */
  UNKNOWN_ACTION(0),
  /**
   * <code>LOGIN_ACTION = 1;</code>
   */
  LOGIN_ACTION(1),
  /**
   * <code>REGISTER_ACTION = 2;</code>
   */
  REGISTER_ACTION(2),
  /**
   * <code>CHECK_EMAIL = 3;</code>
   */
  CHECK_EMAIL(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>UNKNOWN_ACTION = 0;</code>
   */
  public static final int UNKNOWN_ACTION_VALUE = 0;
  /**
   * <code>LOGIN_ACTION = 1;</code>
   */
  public static final int LOGIN_ACTION_VALUE = 1;
  /**
   * <code>REGISTER_ACTION = 2;</code>
   */
  public static final int REGISTER_ACTION_VALUE = 2;
  /**
   * <code>CHECK_EMAIL = 3;</code>
   */
  public static final int CHECK_EMAIL_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ActionType valueOf(int value) {
    return forNumber(value);
  }

  public static ActionType forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN_ACTION;
      case 1: return LOGIN_ACTION;
      case 2: return REGISTER_ACTION;
      case 3: return CHECK_EMAIL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ActionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
          public ActionType findValueByNumber(int number) {
            return ActionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.demo.grpc.proto.User.getDescriptor().getEnumTypes().get(0);
  }

  private static final ActionType[] VALUES = values();

  public static ActionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ActionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.demo.grpc.proto.ActionType)
}

