// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.demo.grpc.proto;

public final class Booking {
  private Booking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_grpc_proto_BookingMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_grpc_proto_BookingMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rbooking.proto\022\023com.demo.grpc.proto\032\022bo" +
      "oking_enum.proto\032\023booking_reply.proto\"\336\001" +
      "\n\016BookingMessage\022\021\n\tbookingId\030\001 \001(\005\022\016\n\006r" +
      "oomId\030\002 \001(\005\022\017\n\007guestId\030\003 \001(\005\022\025\n\rguestLas" +
      "tname\030\004 \001(\t\022\026\n\016guestFirstname\030\005 \001(\t\022\023\n\013c" +
      "heckinTime\030\006 \001(\t\022\024\n\014checkoutTime\030\007 \001(\t\022\016" +
      "\n\006active\030\010 \001(\010\022.\n\004type\030\t \001(\0162 .com.demo." +
      "grpc.proto.BookingType2`\n\016BookingService" +
      "\022N\n\004Send\022#.com.demo.grpc.proto.BookingMe" +
      "ssage\032!.com.demo.grpc.proto.BookingReply",
      "B\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.demo.grpc.proto.BookingEnum.getDescriptor(),
          com.demo.grpc.proto.BookingReplyOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_demo_grpc_proto_BookingMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_grpc_proto_BookingMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_grpc_proto_BookingMessage_descriptor,
        new java.lang.String[] { "BookingId", "RoomId", "GuestId", "GuestLastname", "GuestFirstname", "CheckinTime", "CheckoutTime", "Active", "Type", });
    com.demo.grpc.proto.BookingEnum.getDescriptor();
    com.demo.grpc.proto.BookingReplyOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
