// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking.proto

package com.demo.grpc.proto;

public interface BookingMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.proto.BookingMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bookingId = 1;</code>
   */
  int getBookingId();

  /**
   * <code>int32 roomId = 2;</code>
   */
  int getRoomId();

  /**
   * <code>int32 guestId = 3;</code>
   */
  int getGuestId();

  /**
   * <code>string guestLastname = 4;</code>
   */
  java.lang.String getGuestLastname();
  /**
   * <code>string guestLastname = 4;</code>
   */
  com.google.protobuf.ByteString
      getGuestLastnameBytes();

  /**
   * <code>string guestFirstname = 5;</code>
   */
  java.lang.String getGuestFirstname();
  /**
   * <code>string guestFirstname = 5;</code>
   */
  com.google.protobuf.ByteString
      getGuestFirstnameBytes();

  /**
   * <code>string checkinTime = 6;</code>
   */
  java.lang.String getCheckinTime();
  /**
   * <code>string checkinTime = 6;</code>
   */
  com.google.protobuf.ByteString
      getCheckinTimeBytes();

  /**
   * <code>string checkoutTime = 7;</code>
   */
  java.lang.String getCheckoutTime();
  /**
   * <code>string checkoutTime = 7;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutTimeBytes();

  /**
   * <code>bool active = 8;</code>
   */
  boolean getActive();

  /**
   * <code>.com.demo.grpc.proto.BookingType type = 9;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.demo.grpc.proto.BookingType type = 9;</code>
   */
  com.demo.grpc.proto.BookingType getType();
}
