// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking_reply.proto

package com.demo.grpc.proto;

public final class BookingReplyOuterClass {
  private BookingReplyOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_grpc_proto_BookingReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_grpc_proto_BookingReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023booking_reply.proto\022\023com.demo.grpc.pro" +
      "to\032\022booking_enum.proto\"\307\002\n\014BookingReply\022" +
      "\021\n\tbookingId\030\001 \001(\005\022\016\n\006roomId\030\002 \001(\005\022\020\n\010ro" +
      "omName\030\003 \001(\t\022\017\n\007guestId\030\004 \001(\005\022\025\n\rguestLa" +
      "stname\030\005 \001(\t\022\026\n\016guestFirstname\030\006 \001(\t\022\023\n\013" +
      "checkinTime\030\007 \001(\t\022\024\n\014checkoutTime\030\010 \001(\t\022" +
      "\021\n\tcreatedAt\030\t \001(\t\022\020\n\010updateAt\030\n \001(\t\022\016\n\006" +
      "active\030\013 \001(\010\022.\n\004type\030\014 \001(\0162 .com.demo.gr" +
      "pc.proto.BookingType\0222\n\006status\030\r \001(\0162\".c" +
      "om.demo.grpc.proto.BookingStatusB\002P\001b\006pr",
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.demo.grpc.proto.BookingEnum.getDescriptor(),
        }, assigner);
    internal_static_com_demo_grpc_proto_BookingReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_grpc_proto_BookingReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_grpc_proto_BookingReply_descriptor,
        new java.lang.String[] { "BookingId", "RoomId", "RoomName", "GuestId", "GuestLastname", "GuestFirstname", "CheckinTime", "CheckoutTime", "CreatedAt", "UpdateAt", "Active", "Type", "Status", });
    com.demo.grpc.proto.BookingEnum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
