// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking_reply.proto

package com.demo.grpc.proto;

/**
 * Protobuf type {@code com.demo.grpc.proto.BookingReply}
 */
public  final class BookingReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.demo.grpc.proto.BookingReply)
    BookingReplyOrBuilder {
  // Use BookingReply.newBuilder() to construct.
  private BookingReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BookingReply() {
    bookingId_ = 0;
    roomId_ = 0;
    roomName_ = "";
    guestId_ = 0;
    guestLastname_ = "";
    guestFirstname_ = "";
    checkinTime_ = "";
    checkoutTime_ = "";
    createdAt_ = "";
    updateAt_ = "";
    active_ = false;
    type_ = 0;
    status_ = 0;
    code_ = 0;
    desc_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private BookingReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            bookingId_ = input.readInt32();
            break;
          }
          case 16: {

            roomId_ = input.readInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            roomName_ = s;
            break;
          }
          case 32: {

            guestId_ = input.readInt32();
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            guestLastname_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            guestFirstname_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            checkinTime_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            checkoutTime_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            createdAt_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            updateAt_ = s;
            break;
          }
          case 88: {

            active_ = input.readBool();
            break;
          }
          case 96: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 104: {
            int rawValue = input.readEnum();

            status_ = rawValue;
            break;
          }
          case 112: {

            code_ = input.readInt32();
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            desc_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.demo.grpc.proto.BookingReplyOuterClass.internal_static_com_demo_grpc_proto_BookingReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.demo.grpc.proto.BookingReplyOuterClass.internal_static_com_demo_grpc_proto_BookingReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.demo.grpc.proto.BookingReply.class, com.demo.grpc.proto.BookingReply.Builder.class);
  }

  public static final int BOOKINGID_FIELD_NUMBER = 1;
  private int bookingId_;
  /**
   * <code>int32 bookingId = 1;</code>
   */
  public int getBookingId() {
    return bookingId_;
  }

  public static final int ROOMID_FIELD_NUMBER = 2;
  private int roomId_;
  /**
   * <code>int32 roomId = 2;</code>
   */
  public int getRoomId() {
    return roomId_;
  }

  public static final int ROOMNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object roomName_;
  /**
   * <code>string roomName = 3;</code>
   */
  public java.lang.String getRoomName() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      roomName_ = s;
      return s;
    }
  }
  /**
   * <code>string roomName = 3;</code>
   */
  public com.google.protobuf.ByteString
      getRoomNameBytes() {
    java.lang.Object ref = roomName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      roomName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GUESTID_FIELD_NUMBER = 4;
  private int guestId_;
  /**
   * <code>int32 guestId = 4;</code>
   */
  public int getGuestId() {
    return guestId_;
  }

  public static final int GUESTLASTNAME_FIELD_NUMBER = 5;
  private volatile java.lang.Object guestLastname_;
  /**
   * <code>string guestLastname = 5;</code>
   */
  public java.lang.String getGuestLastname() {
    java.lang.Object ref = guestLastname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      guestLastname_ = s;
      return s;
    }
  }
  /**
   * <code>string guestLastname = 5;</code>
   */
  public com.google.protobuf.ByteString
      getGuestLastnameBytes() {
    java.lang.Object ref = guestLastname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guestLastname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GUESTFIRSTNAME_FIELD_NUMBER = 6;
  private volatile java.lang.Object guestFirstname_;
  /**
   * <code>string guestFirstname = 6;</code>
   */
  public java.lang.String getGuestFirstname() {
    java.lang.Object ref = guestFirstname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      guestFirstname_ = s;
      return s;
    }
  }
  /**
   * <code>string guestFirstname = 6;</code>
   */
  public com.google.protobuf.ByteString
      getGuestFirstnameBytes() {
    java.lang.Object ref = guestFirstname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      guestFirstname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKINTIME_FIELD_NUMBER = 7;
  private volatile java.lang.Object checkinTime_;
  /**
   * <code>string checkinTime = 7;</code>
   */
  public java.lang.String getCheckinTime() {
    java.lang.Object ref = checkinTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checkinTime_ = s;
      return s;
    }
  }
  /**
   * <code>string checkinTime = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCheckinTimeBytes() {
    java.lang.Object ref = checkinTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checkinTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHECKOUTTIME_FIELD_NUMBER = 8;
  private volatile java.lang.Object checkoutTime_;
  /**
   * <code>string checkoutTime = 8;</code>
   */
  public java.lang.String getCheckoutTime() {
    java.lang.Object ref = checkoutTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      checkoutTime_ = s;
      return s;
    }
  }
  /**
   * <code>string checkoutTime = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCheckoutTimeBytes() {
    java.lang.Object ref = checkoutTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      checkoutTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDAT_FIELD_NUMBER = 9;
  private volatile java.lang.Object createdAt_;
  /**
   * <code>string createdAt = 9;</code>
   */
  public java.lang.String getCreatedAt() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdAt_ = s;
      return s;
    }
  }
  /**
   * <code>string createdAt = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedAtBytes() {
    java.lang.Object ref = createdAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATEAT_FIELD_NUMBER = 10;
  private volatile java.lang.Object updateAt_;
  /**
   * <code>string updateAt = 10;</code>
   */
  public java.lang.String getUpdateAt() {
    java.lang.Object ref = updateAt_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updateAt_ = s;
      return s;
    }
  }
  /**
   * <code>string updateAt = 10;</code>
   */
  public com.google.protobuf.ByteString
      getUpdateAtBytes() {
    java.lang.Object ref = updateAt_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updateAt_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTIVE_FIELD_NUMBER = 11;
  private boolean active_;
  /**
   * <code>bool active = 11;</code>
   */
  public boolean getActive() {
    return active_;
  }

  public static final int TYPE_FIELD_NUMBER = 12;
  private int type_;
  /**
   * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
   */
  public com.demo.grpc.proto.BookingType getType() {
    com.demo.grpc.proto.BookingType result = com.demo.grpc.proto.BookingType.valueOf(type_);
    return result == null ? com.demo.grpc.proto.BookingType.UNRECOGNIZED : result;
  }

  public static final int STATUS_FIELD_NUMBER = 13;
  private int status_;
  /**
   * <code>.com.demo.grpc.proto.Status status = 13;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.com.demo.grpc.proto.Status status = 13;</code>
   */
  public com.demo.grpc.proto.Status getStatus() {
    com.demo.grpc.proto.Status result = com.demo.grpc.proto.Status.valueOf(status_);
    return result == null ? com.demo.grpc.proto.Status.UNRECOGNIZED : result;
  }

  public static final int CODE_FIELD_NUMBER = 14;
  private int code_;
  /**
   * <code>int32 code = 14;</code>
   */
  public int getCode() {
    return code_;
  }

  public static final int DESC_FIELD_NUMBER = 15;
  private volatile java.lang.Object desc_;
  /**
   * <code>string desc = 15;</code>
   */
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 15;</code>
   */
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bookingId_ != 0) {
      output.writeInt32(1, bookingId_);
    }
    if (roomId_ != 0) {
      output.writeInt32(2, roomId_);
    }
    if (!getRoomNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, roomName_);
    }
    if (guestId_ != 0) {
      output.writeInt32(4, guestId_);
    }
    if (!getGuestLastnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, guestLastname_);
    }
    if (!getGuestFirstnameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, guestFirstname_);
    }
    if (!getCheckinTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, checkinTime_);
    }
    if (!getCheckoutTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, checkoutTime_);
    }
    if (!getCreatedAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, createdAt_);
    }
    if (!getUpdateAtBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, updateAt_);
    }
    if (active_ != false) {
      output.writeBool(11, active_);
    }
    if (type_ != com.demo.grpc.proto.BookingType.UNKNOWN_TYPE.getNumber()) {
      output.writeEnum(12, type_);
    }
    if (status_ != com.demo.grpc.proto.Status.UNKNOWN.getNumber()) {
      output.writeEnum(13, status_);
    }
    if (code_ != 0) {
      output.writeInt32(14, code_);
    }
    if (!getDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, desc_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bookingId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, bookingId_);
    }
    if (roomId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, roomId_);
    }
    if (!getRoomNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, roomName_);
    }
    if (guestId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, guestId_);
    }
    if (!getGuestLastnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, guestLastname_);
    }
    if (!getGuestFirstnameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, guestFirstname_);
    }
    if (!getCheckinTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, checkinTime_);
    }
    if (!getCheckoutTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, checkoutTime_);
    }
    if (!getCreatedAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, createdAt_);
    }
    if (!getUpdateAtBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, updateAt_);
    }
    if (active_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, active_);
    }
    if (type_ != com.demo.grpc.proto.BookingType.UNKNOWN_TYPE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(12, type_);
    }
    if (status_ != com.demo.grpc.proto.Status.UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(13, status_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(14, code_);
    }
    if (!getDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, desc_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.demo.grpc.proto.BookingReply)) {
      return super.equals(obj);
    }
    com.demo.grpc.proto.BookingReply other = (com.demo.grpc.proto.BookingReply) obj;

    boolean result = true;
    result = result && (getBookingId()
        == other.getBookingId());
    result = result && (getRoomId()
        == other.getRoomId());
    result = result && getRoomName()
        .equals(other.getRoomName());
    result = result && (getGuestId()
        == other.getGuestId());
    result = result && getGuestLastname()
        .equals(other.getGuestLastname());
    result = result && getGuestFirstname()
        .equals(other.getGuestFirstname());
    result = result && getCheckinTime()
        .equals(other.getCheckinTime());
    result = result && getCheckoutTime()
        .equals(other.getCheckoutTime());
    result = result && getCreatedAt()
        .equals(other.getCreatedAt());
    result = result && getUpdateAt()
        .equals(other.getUpdateAt());
    result = result && (getActive()
        == other.getActive());
    result = result && type_ == other.type_;
    result = result && status_ == other.status_;
    result = result && (getCode()
        == other.getCode());
    result = result && getDesc()
        .equals(other.getDesc());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOOKINGID_FIELD_NUMBER;
    hash = (53 * hash) + getBookingId();
    hash = (37 * hash) + ROOMID_FIELD_NUMBER;
    hash = (53 * hash) + getRoomId();
    hash = (37 * hash) + ROOMNAME_FIELD_NUMBER;
    hash = (53 * hash) + getRoomName().hashCode();
    hash = (37 * hash) + GUESTID_FIELD_NUMBER;
    hash = (53 * hash) + getGuestId();
    hash = (37 * hash) + GUESTLASTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGuestLastname().hashCode();
    hash = (37 * hash) + GUESTFIRSTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getGuestFirstname().hashCode();
    hash = (37 * hash) + CHECKINTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCheckinTime().hashCode();
    hash = (37 * hash) + CHECKOUTTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCheckoutTime().hashCode();
    hash = (37 * hash) + CREATEDAT_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedAt().hashCode();
    hash = (37 * hash) + UPDATEAT_FIELD_NUMBER;
    hash = (53 * hash) + getUpdateAt().hashCode();
    hash = (37 * hash) + ACTIVE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getActive());
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.demo.grpc.proto.BookingReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.grpc.proto.BookingReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.demo.grpc.proto.BookingReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.grpc.proto.BookingReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.demo.grpc.proto.BookingReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.demo.grpc.proto.BookingReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.demo.grpc.proto.BookingReply)
      com.demo.grpc.proto.BookingReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.proto.BookingReplyOuterClass.internal_static_com_demo_grpc_proto_BookingReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.proto.BookingReplyOuterClass.internal_static_com_demo_grpc_proto_BookingReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.proto.BookingReply.class, com.demo.grpc.proto.BookingReply.Builder.class);
    }

    // Construct using com.demo.grpc.proto.BookingReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      bookingId_ = 0;

      roomId_ = 0;

      roomName_ = "";

      guestId_ = 0;

      guestLastname_ = "";

      guestFirstname_ = "";

      checkinTime_ = "";

      checkoutTime_ = "";

      createdAt_ = "";

      updateAt_ = "";

      active_ = false;

      type_ = 0;

      status_ = 0;

      code_ = 0;

      desc_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.demo.grpc.proto.BookingReplyOuterClass.internal_static_com_demo_grpc_proto_BookingReply_descriptor;
    }

    public com.demo.grpc.proto.BookingReply getDefaultInstanceForType() {
      return com.demo.grpc.proto.BookingReply.getDefaultInstance();
    }

    public com.demo.grpc.proto.BookingReply build() {
      com.demo.grpc.proto.BookingReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.demo.grpc.proto.BookingReply buildPartial() {
      com.demo.grpc.proto.BookingReply result = new com.demo.grpc.proto.BookingReply(this);
      result.bookingId_ = bookingId_;
      result.roomId_ = roomId_;
      result.roomName_ = roomName_;
      result.guestId_ = guestId_;
      result.guestLastname_ = guestLastname_;
      result.guestFirstname_ = guestFirstname_;
      result.checkinTime_ = checkinTime_;
      result.checkoutTime_ = checkoutTime_;
      result.createdAt_ = createdAt_;
      result.updateAt_ = updateAt_;
      result.active_ = active_;
      result.type_ = type_;
      result.status_ = status_;
      result.code_ = code_;
      result.desc_ = desc_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.demo.grpc.proto.BookingReply) {
        return mergeFrom((com.demo.grpc.proto.BookingReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.demo.grpc.proto.BookingReply other) {
      if (other == com.demo.grpc.proto.BookingReply.getDefaultInstance()) return this;
      if (other.getBookingId() != 0) {
        setBookingId(other.getBookingId());
      }
      if (other.getRoomId() != 0) {
        setRoomId(other.getRoomId());
      }
      if (!other.getRoomName().isEmpty()) {
        roomName_ = other.roomName_;
        onChanged();
      }
      if (other.getGuestId() != 0) {
        setGuestId(other.getGuestId());
      }
      if (!other.getGuestLastname().isEmpty()) {
        guestLastname_ = other.guestLastname_;
        onChanged();
      }
      if (!other.getGuestFirstname().isEmpty()) {
        guestFirstname_ = other.guestFirstname_;
        onChanged();
      }
      if (!other.getCheckinTime().isEmpty()) {
        checkinTime_ = other.checkinTime_;
        onChanged();
      }
      if (!other.getCheckoutTime().isEmpty()) {
        checkoutTime_ = other.checkoutTime_;
        onChanged();
      }
      if (!other.getCreatedAt().isEmpty()) {
        createdAt_ = other.createdAt_;
        onChanged();
      }
      if (!other.getUpdateAt().isEmpty()) {
        updateAt_ = other.updateAt_;
        onChanged();
      }
      if (other.getActive() != false) {
        setActive(other.getActive());
      }
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.demo.grpc.proto.BookingReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.demo.grpc.proto.BookingReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bookingId_ ;
    /**
     * <code>int32 bookingId = 1;</code>
     */
    public int getBookingId() {
      return bookingId_;
    }
    /**
     * <code>int32 bookingId = 1;</code>
     */
    public Builder setBookingId(int value) {
      
      bookingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bookingId = 1;</code>
     */
    public Builder clearBookingId() {
      
      bookingId_ = 0;
      onChanged();
      return this;
    }

    private int roomId_ ;
    /**
     * <code>int32 roomId = 2;</code>
     */
    public int getRoomId() {
      return roomId_;
    }
    /**
     * <code>int32 roomId = 2;</code>
     */
    public Builder setRoomId(int value) {
      
      roomId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roomId = 2;</code>
     */
    public Builder clearRoomId() {
      
      roomId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object roomName_ = "";
    /**
     * <code>string roomName = 3;</code>
     */
    public java.lang.String getRoomName() {
      java.lang.Object ref = roomName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        roomName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string roomName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRoomNameBytes() {
      java.lang.Object ref = roomName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roomName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string roomName = 3;</code>
     */
    public Builder setRoomName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      roomName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string roomName = 3;</code>
     */
    public Builder clearRoomName() {
      
      roomName_ = getDefaultInstance().getRoomName();
      onChanged();
      return this;
    }
    /**
     * <code>string roomName = 3;</code>
     */
    public Builder setRoomNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      roomName_ = value;
      onChanged();
      return this;
    }

    private int guestId_ ;
    /**
     * <code>int32 guestId = 4;</code>
     */
    public int getGuestId() {
      return guestId_;
    }
    /**
     * <code>int32 guestId = 4;</code>
     */
    public Builder setGuestId(int value) {
      
      guestId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 guestId = 4;</code>
     */
    public Builder clearGuestId() {
      
      guestId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object guestLastname_ = "";
    /**
     * <code>string guestLastname = 5;</code>
     */
    public java.lang.String getGuestLastname() {
      java.lang.Object ref = guestLastname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guestLastname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string guestLastname = 5;</code>
     */
    public com.google.protobuf.ByteString
        getGuestLastnameBytes() {
      java.lang.Object ref = guestLastname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guestLastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string guestLastname = 5;</code>
     */
    public Builder setGuestLastname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      guestLastname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string guestLastname = 5;</code>
     */
    public Builder clearGuestLastname() {
      
      guestLastname_ = getDefaultInstance().getGuestLastname();
      onChanged();
      return this;
    }
    /**
     * <code>string guestLastname = 5;</code>
     */
    public Builder setGuestLastnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      guestLastname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object guestFirstname_ = "";
    /**
     * <code>string guestFirstname = 6;</code>
     */
    public java.lang.String getGuestFirstname() {
      java.lang.Object ref = guestFirstname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        guestFirstname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string guestFirstname = 6;</code>
     */
    public com.google.protobuf.ByteString
        getGuestFirstnameBytes() {
      java.lang.Object ref = guestFirstname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        guestFirstname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string guestFirstname = 6;</code>
     */
    public Builder setGuestFirstname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      guestFirstname_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string guestFirstname = 6;</code>
     */
    public Builder clearGuestFirstname() {
      
      guestFirstname_ = getDefaultInstance().getGuestFirstname();
      onChanged();
      return this;
    }
    /**
     * <code>string guestFirstname = 6;</code>
     */
    public Builder setGuestFirstnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      guestFirstname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object checkinTime_ = "";
    /**
     * <code>string checkinTime = 7;</code>
     */
    public java.lang.String getCheckinTime() {
      java.lang.Object ref = checkinTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checkinTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checkinTime = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCheckinTimeBytes() {
      java.lang.Object ref = checkinTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checkinTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checkinTime = 7;</code>
     */
    public Builder setCheckinTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      checkinTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string checkinTime = 7;</code>
     */
    public Builder clearCheckinTime() {
      
      checkinTime_ = getDefaultInstance().getCheckinTime();
      onChanged();
      return this;
    }
    /**
     * <code>string checkinTime = 7;</code>
     */
    public Builder setCheckinTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      checkinTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object checkoutTime_ = "";
    /**
     * <code>string checkoutTime = 8;</code>
     */
    public java.lang.String getCheckoutTime() {
      java.lang.Object ref = checkoutTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        checkoutTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string checkoutTime = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCheckoutTimeBytes() {
      java.lang.Object ref = checkoutTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        checkoutTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string checkoutTime = 8;</code>
     */
    public Builder setCheckoutTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      checkoutTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string checkoutTime = 8;</code>
     */
    public Builder clearCheckoutTime() {
      
      checkoutTime_ = getDefaultInstance().getCheckoutTime();
      onChanged();
      return this;
    }
    /**
     * <code>string checkoutTime = 8;</code>
     */
    public Builder setCheckoutTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      checkoutTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdAt_ = "";
    /**
     * <code>string createdAt = 9;</code>
     */
    public java.lang.String getCreatedAt() {
      java.lang.Object ref = createdAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string createdAt = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedAtBytes() {
      java.lang.Object ref = createdAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string createdAt = 9;</code>
     */
    public Builder setCreatedAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string createdAt = 9;</code>
     */
    public Builder clearCreatedAt() {
      
      createdAt_ = getDefaultInstance().getCreatedAt();
      onChanged();
      return this;
    }
    /**
     * <code>string createdAt = 9;</code>
     */
    public Builder setCreatedAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdAt_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updateAt_ = "";
    /**
     * <code>string updateAt = 10;</code>
     */
    public java.lang.String getUpdateAt() {
      java.lang.Object ref = updateAt_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updateAt_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string updateAt = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUpdateAtBytes() {
      java.lang.Object ref = updateAt_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updateAt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string updateAt = 10;</code>
     */
    public Builder setUpdateAt(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updateAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string updateAt = 10;</code>
     */
    public Builder clearUpdateAt() {
      
      updateAt_ = getDefaultInstance().getUpdateAt();
      onChanged();
      return this;
    }
    /**
     * <code>string updateAt = 10;</code>
     */
    public Builder setUpdateAtBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updateAt_ = value;
      onChanged();
      return this;
    }

    private boolean active_ ;
    /**
     * <code>bool active = 11;</code>
     */
    public boolean getActive() {
      return active_;
    }
    /**
     * <code>bool active = 11;</code>
     */
    public Builder setActive(boolean value) {
      
      active_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool active = 11;</code>
     */
    public Builder clearActive() {
      
      active_ = false;
      onChanged();
      return this;
    }

    private int type_ = 0;
    /**
     * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
     */
    public com.demo.grpc.proto.BookingType getType() {
      com.demo.grpc.proto.BookingType result = com.demo.grpc.proto.BookingType.valueOf(type_);
      return result == null ? com.demo.grpc.proto.BookingType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
     */
    public Builder setType(com.demo.grpc.proto.BookingType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.com.demo.grpc.proto.Status status = 13;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.com.demo.grpc.proto.Status status = 13;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.demo.grpc.proto.Status status = 13;</code>
     */
    public com.demo.grpc.proto.Status getStatus() {
      com.demo.grpc.proto.Status result = com.demo.grpc.proto.Status.valueOf(status_);
      return result == null ? com.demo.grpc.proto.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.demo.grpc.proto.Status status = 13;</code>
     */
    public Builder setStatus(com.demo.grpc.proto.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.demo.grpc.proto.Status status = 13;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <code>int32 code = 14;</code>
     */
    public int getCode() {
      return code_;
    }
    /**
     * <code>int32 code = 14;</code>
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 code = 14;</code>
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 15;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 15;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 15;</code>
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      desc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 15;</code>
     */
    public Builder clearDesc() {
      
      desc_ = getDefaultInstance().getDesc();
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 15;</code>
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      desc_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.demo.grpc.proto.BookingReply)
  }

  // @@protoc_insertion_point(class_scope:com.demo.grpc.proto.BookingReply)
  private static final com.demo.grpc.proto.BookingReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.demo.grpc.proto.BookingReply();
  }

  public static com.demo.grpc.proto.BookingReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BookingReply>
      PARSER = new com.google.protobuf.AbstractParser<BookingReply>() {
    public BookingReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookingReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BookingReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BookingReply> getParserForType() {
    return PARSER;
  }

  public com.demo.grpc.proto.BookingReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

