// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: booking_reply.proto

package com.demo.grpc.proto;

public interface BookingReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.proto.BookingReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bookingId = 1;</code>
   */
  int getBookingId();

  /**
   * <code>int32 roomId = 2;</code>
   */
  int getRoomId();

  /**
   * <code>string roomName = 3;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 3;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>int32 guestId = 4;</code>
   */
  int getGuestId();

  /**
   * <code>string guestLastname = 5;</code>
   */
  java.lang.String getGuestLastname();
  /**
   * <code>string guestLastname = 5;</code>
   */
  com.google.protobuf.ByteString
      getGuestLastnameBytes();

  /**
   * <code>string guestFirstname = 6;</code>
   */
  java.lang.String getGuestFirstname();
  /**
   * <code>string guestFirstname = 6;</code>
   */
  com.google.protobuf.ByteString
      getGuestFirstnameBytes();

  /**
   * <code>string checkinTime = 7;</code>
   */
  java.lang.String getCheckinTime();
  /**
   * <code>string checkinTime = 7;</code>
   */
  com.google.protobuf.ByteString
      getCheckinTimeBytes();

  /**
   * <code>string checkoutTime = 8;</code>
   */
  java.lang.String getCheckoutTime();
  /**
   * <code>string checkoutTime = 8;</code>
   */
  com.google.protobuf.ByteString
      getCheckoutTimeBytes();

  /**
   * <code>string createdAt = 9;</code>
   */
  java.lang.String getCreatedAt();
  /**
   * <code>string createdAt = 9;</code>
   */
  com.google.protobuf.ByteString
      getCreatedAtBytes();

  /**
   * <code>string updateAt = 10;</code>
   */
  java.lang.String getUpdateAt();
  /**
   * <code>string updateAt = 10;</code>
   */
  com.google.protobuf.ByteString
      getUpdateAtBytes();

  /**
   * <code>bool active = 11;</code>
   */
  boolean getActive();

  /**
   * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
   */
  int getTypeValue();
  /**
   * <code>.com.demo.grpc.proto.BookingType type = 12;</code>
   */
  com.demo.grpc.proto.BookingType getType();

  /**
   * <code>.com.demo.grpc.proto.Status status = 13;</code>
   */
  int getStatusValue();
  /**
   * <code>.com.demo.grpc.proto.Status status = 13;</code>
   */
  com.demo.grpc.proto.Status getStatus();

  /**
   * <code>int32 code = 14;</code>
   */
  int getCode();

  /**
   * <code>string desc = 15;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 15;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
