// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_booking.proto

package com.demo.grpc.proto;

public final class SearchBooking {
  private SearchBooking() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_grpc_proto_SearchMessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_grpc_proto_SearchMessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_demo_grpc_proto_SearchMessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_demo_grpc_proto_SearchMessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024search_booking.proto\022\023com.demo.grpc.pr" +
      "oto\032\023booking_reply.proto\"U\n\024SearchMessag" +
      "eRequest\022\017\n\007guestId\030\001 \001(\005\022\014\n\004page\030\002 \001(\005\022" +
      "\014\n\004size\030\003 \001(\005\022\020\n\010isActive\030\004 \001(\010\"h\n\025Searc" +
      "hMessageResponse\0223\n\010bookings\030\001 \003(\0132!.com" +
      ".demo.grpc.proto.BookingReply\022\014\n\004page\030\002 " +
      "\001(\005\022\014\n\004size\030\003 \001(\0052p\n\rSearchService\022_\n\006Se" +
      "arch\022).com.demo.grpc.proto.SearchMessage" +
      "Request\032*.com.demo.grpc.proto.SearchMess" +
      "ageResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.demo.grpc.proto.BookingReplyOuterClass.getDescriptor(),
        }, assigner);
    internal_static_com_demo_grpc_proto_SearchMessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_demo_grpc_proto_SearchMessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_grpc_proto_SearchMessageRequest_descriptor,
        new java.lang.String[] { "GuestId", "Page", "Size", "IsActive", });
    internal_static_com_demo_grpc_proto_SearchMessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_demo_grpc_proto_SearchMessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_demo_grpc_proto_SearchMessageResponse_descriptor,
        new java.lang.String[] { "Bookings", "Page", "Size", });
    com.demo.grpc.proto.BookingReplyOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
