// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_booking.proto

package com.demo.grpc.proto;

public interface SearchMessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.proto.SearchMessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 guestId = 1;</code>
   */
  int getGuestId();

  /**
   * <code>int32 page = 2;</code>
   */
  int getPage();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();

  /**
   * <code>bool isActive = 4;</code>
   */
  boolean getIsActive();
}
