// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_booking.proto

package com.demo.grpc.proto;

/**
 * Protobuf type {@code com.demo.grpc.proto.SearchMessageResponse}
 */
public  final class SearchMessageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.demo.grpc.proto.SearchMessageResponse)
    SearchMessageResponseOrBuilder {
  // Use SearchMessageResponse.newBuilder() to construct.
  private SearchMessageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SearchMessageResponse() {
    bookings_ = java.util.Collections.emptyList();
    page_ = 0;
    size_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SearchMessageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              bookings_ = new java.util.ArrayList<com.demo.grpc.proto.BookingReply>();
              mutable_bitField0_ |= 0x00000001;
            }
            bookings_.add(
                input.readMessage(com.demo.grpc.proto.BookingReply.parser(), extensionRegistry));
            break;
          }
          case 16: {

            page_ = input.readInt32();
            break;
          }
          case 24: {

            size_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        bookings_ = java.util.Collections.unmodifiableList(bookings_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.demo.grpc.proto.SearchBooking.internal_static_com_demo_grpc_proto_SearchMessageResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.demo.grpc.proto.SearchBooking.internal_static_com_demo_grpc_proto_SearchMessageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.demo.grpc.proto.SearchMessageResponse.class, com.demo.grpc.proto.SearchMessageResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BOOKINGS_FIELD_NUMBER = 1;
  private java.util.List<com.demo.grpc.proto.BookingReply> bookings_;
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  public java.util.List<com.demo.grpc.proto.BookingReply> getBookingsList() {
    return bookings_;
  }
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  public java.util.List<? extends com.demo.grpc.proto.BookingReplyOrBuilder> 
      getBookingsOrBuilderList() {
    return bookings_;
  }
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  public int getBookingsCount() {
    return bookings_.size();
  }
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  public com.demo.grpc.proto.BookingReply getBookings(int index) {
    return bookings_.get(index);
  }
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  public com.demo.grpc.proto.BookingReplyOrBuilder getBookingsOrBuilder(
      int index) {
    return bookings_.get(index);
  }

  public static final int PAGE_FIELD_NUMBER = 2;
  private int page_;
  /**
   * <code>int32 page = 2;</code>
   */
  public int getPage() {
    return page_;
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private int size_;
  /**
   * <code>int32 size = 3;</code>
   */
  public int getSize() {
    return size_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < bookings_.size(); i++) {
      output.writeMessage(1, bookings_.get(i));
    }
    if (page_ != 0) {
      output.writeInt32(2, page_);
    }
    if (size_ != 0) {
      output.writeInt32(3, size_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < bookings_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, bookings_.get(i));
    }
    if (page_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, page_);
    }
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, size_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.demo.grpc.proto.SearchMessageResponse)) {
      return super.equals(obj);
    }
    com.demo.grpc.proto.SearchMessageResponse other = (com.demo.grpc.proto.SearchMessageResponse) obj;

    boolean result = true;
    result = result && getBookingsList()
        .equals(other.getBookingsList());
    result = result && (getPage()
        == other.getPage());
    result = result && (getSize()
        == other.getSize());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getBookingsCount() > 0) {
      hash = (37 * hash) + BOOKINGS_FIELD_NUMBER;
      hash = (53 * hash) + getBookingsList().hashCode();
    }
    hash = (37 * hash) + PAGE_FIELD_NUMBER;
    hash = (53 * hash) + getPage();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.demo.grpc.proto.SearchMessageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.demo.grpc.proto.SearchMessageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.demo.grpc.proto.SearchMessageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.demo.grpc.proto.SearchMessageResponse)
      com.demo.grpc.proto.SearchMessageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.demo.grpc.proto.SearchBooking.internal_static_com_demo_grpc_proto_SearchMessageResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.demo.grpc.proto.SearchBooking.internal_static_com_demo_grpc_proto_SearchMessageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.demo.grpc.proto.SearchMessageResponse.class, com.demo.grpc.proto.SearchMessageResponse.Builder.class);
    }

    // Construct using com.demo.grpc.proto.SearchMessageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getBookingsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        bookingsBuilder_.clear();
      }
      page_ = 0;

      size_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.demo.grpc.proto.SearchBooking.internal_static_com_demo_grpc_proto_SearchMessageResponse_descriptor;
    }

    public com.demo.grpc.proto.SearchMessageResponse getDefaultInstanceForType() {
      return com.demo.grpc.proto.SearchMessageResponse.getDefaultInstance();
    }

    public com.demo.grpc.proto.SearchMessageResponse build() {
      com.demo.grpc.proto.SearchMessageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.demo.grpc.proto.SearchMessageResponse buildPartial() {
      com.demo.grpc.proto.SearchMessageResponse result = new com.demo.grpc.proto.SearchMessageResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (bookingsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          bookings_ = java.util.Collections.unmodifiableList(bookings_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.bookings_ = bookings_;
      } else {
        result.bookings_ = bookingsBuilder_.build();
      }
      result.page_ = page_;
      result.size_ = size_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.demo.grpc.proto.SearchMessageResponse) {
        return mergeFrom((com.demo.grpc.proto.SearchMessageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.demo.grpc.proto.SearchMessageResponse other) {
      if (other == com.demo.grpc.proto.SearchMessageResponse.getDefaultInstance()) return this;
      if (bookingsBuilder_ == null) {
        if (!other.bookings_.isEmpty()) {
          if (bookings_.isEmpty()) {
            bookings_ = other.bookings_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureBookingsIsMutable();
            bookings_.addAll(other.bookings_);
          }
          onChanged();
        }
      } else {
        if (!other.bookings_.isEmpty()) {
          if (bookingsBuilder_.isEmpty()) {
            bookingsBuilder_.dispose();
            bookingsBuilder_ = null;
            bookings_ = other.bookings_;
            bitField0_ = (bitField0_ & ~0x00000001);
            bookingsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getBookingsFieldBuilder() : null;
          } else {
            bookingsBuilder_.addAllMessages(other.bookings_);
          }
        }
      }
      if (other.getPage() != 0) {
        setPage(other.getPage());
      }
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.demo.grpc.proto.SearchMessageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.demo.grpc.proto.SearchMessageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.demo.grpc.proto.BookingReply> bookings_ =
      java.util.Collections.emptyList();
    private void ensureBookingsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        bookings_ = new java.util.ArrayList<com.demo.grpc.proto.BookingReply>(bookings_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.demo.grpc.proto.BookingReply, com.demo.grpc.proto.BookingReply.Builder, com.demo.grpc.proto.BookingReplyOrBuilder> bookingsBuilder_;

    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public java.util.List<com.demo.grpc.proto.BookingReply> getBookingsList() {
      if (bookingsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(bookings_);
      } else {
        return bookingsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public int getBookingsCount() {
      if (bookingsBuilder_ == null) {
        return bookings_.size();
      } else {
        return bookingsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public com.demo.grpc.proto.BookingReply getBookings(int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);
      } else {
        return bookingsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder setBookings(
        int index, com.demo.grpc.proto.BookingReply value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.set(index, value);
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder setBookings(
        int index, com.demo.grpc.proto.BookingReply.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.set(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder addBookings(com.demo.grpc.proto.BookingReply value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder addBookings(
        int index, com.demo.grpc.proto.BookingReply value) {
      if (bookingsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureBookingsIsMutable();
        bookings_.add(index, value);
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder addBookings(
        com.demo.grpc.proto.BookingReply.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder addBookings(
        int index, com.demo.grpc.proto.BookingReply.Builder builderForValue) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.add(index, builderForValue.build());
        onChanged();
      } else {
        bookingsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder addAllBookings(
        java.lang.Iterable<? extends com.demo.grpc.proto.BookingReply> values) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, bookings_);
        onChanged();
      } else {
        bookingsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder clearBookings() {
      if (bookingsBuilder_ == null) {
        bookings_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        bookingsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public Builder removeBookings(int index) {
      if (bookingsBuilder_ == null) {
        ensureBookingsIsMutable();
        bookings_.remove(index);
        onChanged();
      } else {
        bookingsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public com.demo.grpc.proto.BookingReply.Builder getBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public com.demo.grpc.proto.BookingReplyOrBuilder getBookingsOrBuilder(
        int index) {
      if (bookingsBuilder_ == null) {
        return bookings_.get(index);  } else {
        return bookingsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public java.util.List<? extends com.demo.grpc.proto.BookingReplyOrBuilder> 
         getBookingsOrBuilderList() {
      if (bookingsBuilder_ != null) {
        return bookingsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(bookings_);
      }
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public com.demo.grpc.proto.BookingReply.Builder addBookingsBuilder() {
      return getBookingsFieldBuilder().addBuilder(
          com.demo.grpc.proto.BookingReply.getDefaultInstance());
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public com.demo.grpc.proto.BookingReply.Builder addBookingsBuilder(
        int index) {
      return getBookingsFieldBuilder().addBuilder(
          index, com.demo.grpc.proto.BookingReply.getDefaultInstance());
    }
    /**
     * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
     */
    public java.util.List<com.demo.grpc.proto.BookingReply.Builder> 
         getBookingsBuilderList() {
      return getBookingsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.demo.grpc.proto.BookingReply, com.demo.grpc.proto.BookingReply.Builder, com.demo.grpc.proto.BookingReplyOrBuilder> 
        getBookingsFieldBuilder() {
      if (bookingsBuilder_ == null) {
        bookingsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.demo.grpc.proto.BookingReply, com.demo.grpc.proto.BookingReply.Builder, com.demo.grpc.proto.BookingReplyOrBuilder>(
                bookings_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        bookings_ = null;
      }
      return bookingsBuilder_;
    }

    private int page_ ;
    /**
     * <code>int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }
    /**
     * <code>int32 page = 2;</code>
     */
    public Builder setPage(int value) {
      
      page_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 page = 2;</code>
     */
    public Builder clearPage() {
      
      page_ = 0;
      onChanged();
      return this;
    }

    private int size_ ;
    /**
     * <code>int32 size = 3;</code>
     */
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 3;</code>
     */
    public Builder setSize(int value) {
      
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 3;</code>
     */
    public Builder clearSize() {
      
      size_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:com.demo.grpc.proto.SearchMessageResponse)
  }

  // @@protoc_insertion_point(class_scope:com.demo.grpc.proto.SearchMessageResponse)
  private static final com.demo.grpc.proto.SearchMessageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.demo.grpc.proto.SearchMessageResponse();
  }

  public static com.demo.grpc.proto.SearchMessageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SearchMessageResponse>
      PARSER = new com.google.protobuf.AbstractParser<SearchMessageResponse>() {
    public SearchMessageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SearchMessageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SearchMessageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SearchMessageResponse> getParserForType() {
    return PARSER;
  }

  public com.demo.grpc.proto.SearchMessageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

