// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: search_booking.proto

package com.demo.grpc.proto;

public interface SearchMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.proto.SearchMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  java.util.List<com.demo.grpc.proto.BookingReply> 
      getBookingsList();
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  com.demo.grpc.proto.BookingReply getBookings(int index);
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  int getBookingsCount();
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  java.util.List<? extends com.demo.grpc.proto.BookingReplyOrBuilder> 
      getBookingsOrBuilderList();
  /**
   * <code>repeated .com.demo.grpc.proto.BookingReply bookings = 1;</code>
   */
  com.demo.grpc.proto.BookingReplyOrBuilder getBookingsOrBuilder(
      int index);

  /**
   * <code>int32 page = 2;</code>
   */
  int getPage();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();
}
