// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.demo.grpc.proto;

public interface UserMessageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.demo.grpc.proto.UserMessageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string token = 1;</code>
   */
  java.lang.String getToken();
  /**
   * <code>string token = 1;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>int32 code = 2;</code>
   */
  int getCode();

  /**
   * <code>string desc = 3;</code>
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescBytes();

  /**
   * <code>.com.demo.grpc.proto.Status status = 4;</code>
   */
  int getStatusValue();
  /**
   * <code>.com.demo.grpc.proto.Status status = 4;</code>
   */
  com.demo.grpc.proto.Status getStatus();
}
