spring:
  application:
    name: gateway_service

server:
  port: ${SERVICE_PORT:8081}

grpc:
  booking:
    host: ${BOOKING_SERVICE_ADDRESS:localhost}
    port: ${BOOKING_SERVICE_PORT:9093}
  auth:
    host: ${IDENTITY_SERVICE_ADDRESS:localhost}
    port: ${IDENTITY_SERVICE_PORT:9094}

management:
  endpoint:
    health:
      show-details: ALWAYS

swagger:
  contact-name: Binh Truong
  contact-mail: binhtt.work@gmail.com
  contact-url: https://github.com/binhtt13122000
  app-name: MVP Hotel Booking API
  app-description: ""
  app-version: 1.0.0

jwt:
  secret: 123453434sdasdzxZxZxsdasdsxXzXZXzmx>zxm.zLXXCMZXCZMXLAWDLMMXCMZXCMZX123132